---

- hosts: all
  remote_user: root
  pre_tasks:

  - name: install updates (Fedora)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"



- hosts: web_servers
  remote_user: root
  tasks:

  - name: install apache and php package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest



- hosts: db_server
  remote_user: root
  tasks:

  - name: Install mariadb server package
    apt:
      name: mariadb-server
      state: latest


- hosts: file_server
  remote_user: root
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
